services:
  mysql:
    image: mysql:8.0
    container_name: moneymentor-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: moneymentor
      MYSQL_USER: moneymentor_user
      MYSQL_PASSWORD: moneymentor_pass
    ports:
      - "3308:3306"  # Custom port to avoid conflicts
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - moneymentor-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: moneymentor-redis
    ports:
      - "6381:6379"  # Custom port to avoid conflicts
    volumes:
      - redis_data:/data
    networks:
      - moneymentor-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 10s
      retries: 5
    command: redis-server --appendonly yes

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moneymentor-app
    ports:
      - "8089:8080"  # Custom port to avoid conflicts
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - moneymentor-network
    volumes:
      - ./logs:/app/logs

volumes:
  mysql_data:
  redis_data:

networks:
  moneymentor-network:
    driver: bridge
